In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("WA_Fn-UseC_-HR-Employee-Attrition.csv")

In [6]:
df_sample = df.sample(frac=1).reset_index(drop=True)

In [7]:
df_sample.shape

(1470, 35)

In [8]:
df.shape

(1470, 35)

In [11]:
import uuid
df_sample['id'] = df_sample.apply(lambda _: uuid.uuid4(), axis=1)

In [13]:
cols = list(df_sample.columns)
cols = [cols[-1]] + cols[:-1]
df_sample = df_sample[cols]

In [21]:
from sklearn.model_selection import train_test_split
train , test = train_test_split(df_sample, test_size=0.2, random_state=1)

In [22]:
test[test["Attrition"]=="Yes"].shape[0] / test.shape[0]

0.13945578231292516

In [20]:
train[train["Attrition"]=="Yes"].shape[0] / train.shape[0]

0.1488095238095238

In [23]:
train.to_csv("hr_train.csv", index=False)
test.to_csv("hr_test.csv", index=False)

In [24]:
test.head(30)

,id,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
1291,5ca46720-6bc1-4fe2-968c-edbc306dfedc,48,No,Travel_Rarely,855,Research & Development,4,3,Life Sciences,1,...,3,80,0,11,2,3,10,9,0,8
1153,faa1e149-15e4-4a6c-bc5a-d8e5f81af897,27,No,Travel_Rarely,1302,Research & Development,19,3,Other,1,...,1,80,2,7,3,3,7,7,0,7
720,ae2e1f78-2802-4324-8c64-26db02fb85b5,58,No,Non-Travel,350,Sales,2,3,Medical,1,...,4,80,1,37,0,2,16,9,14,14
763,b5189491-5ea4-4841-bc04-755d5c1bbd85,35,No,Non-Travel,1097,Research & Development,11,2,Medical,1,...,3,80,1,10,3,3,4,0,2,3
976,7fe5d71d-b568-42cb-a6ac-e84bf3a02b77,31,No,Travel_Rarely,1276,Research & Development,2,1,Medical,1,...,3,80,3,1,4,3,1,0,0,0
724,dafddede-726f-4cb6-83fd-68f7fb68a93c,46,No,Non-Travel,1144,Research & Development,7,4,Medical,1,...,3,80,0,7,2,4,1,0,0,0
314,8a4fac5d-859c-4d87-a3e3-cfe9f083eb10,40,No,Travel_Rarely,1300,Research & Development,24,2,Technical Degree,1,...,1,80,2,9,3,3,9,8,4,7
258,fe7e9bbc-accf-47b6-85b2-cc971d3448bf,25,No,Travel_Rarely,1356,Sales,10,4,Life Sciences,1,...,2,80,0,5,4,3,4,3,1,1
442,775906c9-b4fd-4693-acbf-b0d38c7837ca,28,No,Travel_Rarely,821,Sales,5,4,Medical,1,...,2,80,0,4,3,3,4,2,0,2
1393,7cc152bd-bafa-4ac9-9902-6a261e42bc22,30,No,Travel_Rarely,855,Sales,7,4,Marketing,1,...,2,80,2,8,3,3,3,2,0,2
894,2935359a-9786-4ed6-8dff-fb608aa5e58c,35,No,Travel_Rarely,682,Sales,18,4,Medical,1,...,4,80,1,6,2,1,5,3,0,4
435,fe7a3190-8e29-4a52-b7cc-b4b3bd1fc7fb,45,No,Travel_Rarely,374,Sales,20,3,Life Sciences,1,...,3,80,0,8,3,3,5,3,0,1
952,e5257f26-a009-4a50-b2ba-348e4766e103,42,No,Travel_Rarely,855,Research & Development,12,3,Medical,1,...,2,80,3,7,6,2,5,3,0,4
236,c127ad89-dc85-41f0-a2a7-02095058093a,38,No,Travel_Rarely,723,Sales,2,4,Marketing,1,...,1,80,2,20,4,2,4,2,0,3
1170,cfb6bbf4-7e39-465c-b495-4e581a438af4,34,No,Travel_Frequently,669,Research & Development,1,3,Medical,1,...,3,80,0,14,3,3,13,9,4,9
1295,3a3c3412-948b-4703-9a81-f7cb4e52d787,29,No,Travel_Rarely,718,Research & Development,8,1,Medical,1,...,3,80,1,10,2,2,10,7,1,2
826,91e3babc-2611-4825-bb22-d11b435e27da,35,No,Travel_Rarely,1370,Research & Development,27,4,Life Sciences,1,...,2,80,1,17,3,3,7,7,0,7
453,b663422a-79b0-4ba7-bd6f-2a556a1e5193,40,No,Travel_Frequently,1184,Sales,2,4,Medical,1,...,4,80,3,5,2,3,0,0,0,0
1230,dd3badef-a35f-4bd2-a718-7d5d9dad8f9b,35,No,Travel_Frequently,482,Research & Development,4,4,Life Sciences,1,...,2,80,0,9,3,3,9,6,1,1
702,f1ba0efa-aef6-4214-a376-7692f75d6560,36,No,Non-Travel,1351,Research & Development,9,4,Life Sciences,1,...,2,80,0,5,3,3,5,4,0,2
1418,24abf10f-8097-441c-9087-6668b0d9aafb,31,No,Travel_Frequently,1125,Research & Development,1,3,Life Sciences,1,...,2,80,0,10,6,3,10,8,8,7
1252,73a6c3d8-c30e-4aef-b67d-62c73d8c9aa6,24,Yes,Travel_Rarely,693,Sales,3,2,Life Sciences,1,...,1,80,0,4,3,3,2,2,2,0
299,4fe02e14-a17d-4fe3-9f07-fb4905b8892c,51,No,Travel_Frequently,1456,Research & Development,1,4,Medical,1,...,3,80,0,23,1,2,13,12,12,8
53,7eaff092-20b0-42f7-b143-4d9e66f44dcf,49,No,Travel_Rarely,1245,Research & Development,18,4,Life Sciences,1,...,3,80,1,31,5,3,31,9,0,9
993,12c50e41-1e3b-4f05-8d1b-e8d088e18f95,29,Yes,Travel_Frequently,337,Research & Development,14,1,Other,1,...,1,80,0,9,1,3,8,7,7,7
311,01dd8c71-7b67-4158-b118-fa2141c9b7f9,30,No,Travel_Rarely,413,Sales,7,1,Marketing,1,...,1,80,0,4,3,3,3,2,1,2
107,3b22890a-e94c-4be8-bf03-05204a762fc2,46,Yes,Travel_Rarely,377,Sales,9,3,Marketing,1,...,1,80,1,28,1,4,7,7,4,3
37,14ca6f2a-55d6-4eb0-8f7c-1fb499a11b0f,29,No,Travel_Rarely,986,Research & Development,3,4,Medical,1,...,3,80,0,10,2,3,10,2,0,7
864,aa771210-740f-4d97-b87f-1fc9c6f28991,59,No,Non-Travel,1420,Human Resources,2,4,Human Resources,1,...,4,80,1,30,3,3,3,2,2,2
640,6b0a77b1-83de-4df7-8840-3d955bd09fb2,50,No,Travel_Rarely,1046,Research & Development,10,3,Technical Degree,1,...,4,80,0,20,2,3,4,3,1,3